services:
  db:
    image: postgres
    networks:
      - app-network
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - PGUSER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
#      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'"]
      interval: 30s
      timeout: 3s
      start_period: 120s
      start_interval: 20s

  adminer:
    image: adminer
    networks:
      - app-network
    ports:
      - 8080:8080

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
